
export const categoryConstants = {
    ADDCATEGORY_REQUEST: "ADDCATEGORY_REQUEST",
    ADDCATEGORY_SUCCESS: "ADDCATEGORY_SUCCESS",
    ADDCATEGORY_FAILURE: "ADDCATEGORY_FAILURE",

    CATEGORYLIST_REQUEST: "CATEGORYLIST_REQUEST",
    CATEGORYLIST_SUCCESS: "CATEGORYLIST_SUCCESS",
    CATEGORYLIST_FAILURE: "CATEGORYLIST_FAILURE",
}

export const productConstants = {
    ADDPRODUCT_REQUEST: "ADDPRODUCT_REQUEST",
    ADDPRODUCT_SUCCESS: "ADDPRODUCT_SUCCESS",
    ADDPRODUCT_FAILURE: "ADDPRODUCT_FAILURE",

    PRODUCTLIST_REQUEST: "PRODUCTLIST_REQUEST",
    PRODUCTLIST_SUCCESS: "PRODUCTLIST_SUCCESS",
    PRODUCTLIST_FAILURE: "PRODUCTLIST_FAILURE",
}